export const CATEGORY_DATA_REQUEST = "CATEGORY_DATA_REQUEST";
export const CATEGORY_DATA_RESPONSE = "CATEGORY_DATA_RESPONSE";
export const CATEGORY_DATA_FAIL = "CATEGORY_DATA_FAIL";

export const CATEGORY_PRODUCT_REQUEST = "CATEGORY_PRODUCT_REQUEST";
export const CATEGORY_PRODUCT_RESPONSE = "CATEGORY_PRODUCT_RESPONSE";
export const CATEGORY_PRODUCT_FAIL = "CATEGORY_PRODUCT_FAIL";
