export const CATEGORY_ACTIVE_UPDATE = "CATEGORY_ACTIVE_UPDATE";

export const CATEGORY_PRODUCTS_REQUEST = "CATEGORY_PRODUCTS_REQUEST";
export const CATEGORY_PRODUCTS_RESPONSE = "CATEGORY_PRODUCTS_RESPONSE";
export const CATEGORY_PRODUCTS_FAIL = "CATEGORY_PRODUCTS_FAIL";

export const CATEGORY_PRODUCT_REQUEST = "CATEGORY_PRODUCT_REQUEST";
export const CATEGORY_PRODUCT_RESPONSE = "CATEGORY_PRODUCT_RESPONSE";
export const CATEGORY_PRODUCT_FAIL = "CATEGORY_PRODUCT_FAIL";
