export const CURRENCY_DATA_REQUEST = "CURRENCY_DATA_REQUEST";
export const CURRENCY_DATA_RESPONSE = "CURRENCY_DATA_RESPONSE";
export const CURRENCY_DATA_FAIL = "CURRENCY_DATA_FAIL";

export const CURRENCY_ACTIVE_UPDATE = "CURRENCY_ACTIVE_UPDATE";
